### ISSUE TITLE
Would it be useful to have a Jekyll plugin for dart script tags?

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-webdev#16]
_From @srawlins on September 19, 2014 22:6_

In my [Download Archive PR](https://github.com/dart-lang/www.dartlang.org/pull/1040), I have to [load the dart2js-generated Javascript](https://github.com/dart-lang/www.dartlang.org/pull/1040/files#diff-c21344c385e65becc536b0f71cf77912R7) in Jekyll:

```yaml
js:
- url: web/download_archive.dart.js
  defer: true
```

I think it would be simple to have a Jekyll plugin that would allow this syntax:

```yaml
dart:
- url: web/download_archive.dart
  defer: true
```

which would turn into the following HTML:

```html
<script async type="application/dart" src="web/download_archive.dart"></script>
<script async src="web/packages/browser/dart.js"></script>
```

Would this be useful?

_Copied from original issue: dart-lang/www.dartlang.org#1044_
