### ISSUE TITLE
'Codelab: AngularDart Components' page issue

### ISSUE THREAD

**Issue by pet-ro** [dart-lang/site-webdev#1850]
From URL: https://webdev.dartlang.org/codelabs/angular_components
**Current**

<blockquote>

   To complete this codelab, you need the following:
   - A Windows, Mac, or Linux computer with Dart SDK **1.24** (or a higher version)
  <footer>
     <cite><a href="https://webdev.dartlang.org/codelabs/angular_components"
       >Codelab: AngularDart Components</a> titled
       <em></em>.
     </cite>
  </footer>
</blockquote>

**Expected**

<blockquote>

   To complete this codelab, you need the following:
   - A Windows, Mac, or Linux computer with Dart SDK **2.0.0** (or a higher version)
  <footer>
     <cite><a href="https://webdev.dartlang.org/codelabs/angular_components"
       >Codelab: AngularDart Components</a> titled
       <em></em>.
     </cite>
  </footer>
</blockquote>

because `pubspec.yaml` 

https://github.com/angular-examples/lottery/blob/master/1-base/pubspec.yaml

states: 

```yaml
name: components_codelab
description: An AngularDart app that simulates a lottery
version: 0.0.1

environment:
  sdk: '>=2.0.0 <3.0.0'
```
