### ISSUE TITLE
[master] examples/ng/doc/toh-6 testing

### ISSUE THREAD

**Issue by manuscle** [dart-lang/site-webdev#1869]
Hi, I try to make tests working on toh-6
I've cloned the repos then
```
pub get
pub global run webdev build --output=web:build
pub global run webdev serve (to see it working)
```

But when I run tests I get the following errors:
```
pub run test/all_test.dart
Unable to spawn isolate: test/app.dart:6:8: Error: Error when reading 'lib/app_component.template.dart': No such file or directory
import 'package:angular_tour_of_heroes/app_component.template.dart' as ng;
       ^
test/app.dart:12:8: Error: Error when reading 'test/app.template.dart': No such file or directory
import 'app.template.dart' as self;
       ^
test/dashboard.dart:11:8: Error: Error when reading 'lib/src/dashboard_component.template.dart': No such file or directory
import 'package:angular_tour_of_heroes/src/dashboard_component.template.dart'
       ^
lib/src/routes.dart:4:8: Error: Error when reading 'lib/src/dashboard_component.template.dart': No such file or directory
import 'dashboard_component.template.dart' as dashboard_template;
       ^
test/dashboard.dart:19:8: Error: Error when reading 'test/dashboard.template.dart': No such file or directory
import 'dashboard.template.dart' as self;
       ^
test/heroes.dart:8:8: Error: Error when reading 'lib/src/hero_list_component.template.dart': No such file or directory
import 'package:angular_tour_of_heroes/src/hero_list_component.template.dart'
       ^
lib/src/routes.dart:6:8: Error: Error when reading 'lib/src/hero_list_component.template.dart': No such file or directory
import 'hero_list_component.template.dart' as hero_list_template;
       ^
test/heroes.dart:17:8: Error: Error when reading 'test/heroes.template.dart': No such file or directory
import 'heroes.template.dart' as self;
       ^
test/hero.dart:9:8: Error: Error when reading 'lib/src/hero_component.template.dart': No such file or directory
import 'package:angular_tour_of_heroes/src/hero_component.template.dart' as ng;
       ^
lib/src/routes.dart:5:8: Error: Error when reading 'lib/src/hero_component.template.dart': No such file or directory
import 'hero_component.template.dart' as hero_template;
       ^
```
Also Dart analyser report these errors:
```
error: The name '$DashboardPO.create' isn't a type and can't be used in a redirected constructor. (redirect_to_non_class at [angular_tour_of_heroes] test/dashboard_po.dart:10)
error: The name '$HeroDetailPO.create' isn't a type and can't be used in a redirected constructor. (redirect_to_non_class at [angular_tour_of_heroes] test/hero_po.dart:11)
error: The name '$HeroSearchPO.create' isn't a type and can't be used in a redirected constructor. (redirect_to_non_class at [angular_tour_of_heroes] test/hero_search_po.dart:10)
error: The name '$HeroesPO.create' isn't a type and can't be used in a redirected constructor. (redirect_to_non_class at [angular_tour_of_heroes] test/heroes_po.dart:11)
```

**Comment by kwalrath** [comment]
We've had some issues updating template code. @chalin do you think this is related to those?

**Comment by chalin** [comment]
I don't think so, but the example repos are behind. As soon as you (@kwalrath) are done with the PR updating to NG 5.2, then I can sync the repos. (Maybe ping @nshahan to find out when the ACX update will be released?)

Thanks for the issue @manuscle. Can you tell me which version of Dart you are using and copy the app `pubspec.yaml` file here?

**Comment by manuscle** [comment]
I am using dart 2.1.0
There is the pubspec.yaml (same as repos):
```
name: angular_tour_of_heroes
description: Tour of Heroes
version: 0.0.1

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.0.0
  angular_forms: ^2.0.0
  angular_router: ^2.0.0-alpha+19
  http: ^0.11.0
  stream_transform: ^0.0.6

dev_dependencies:
  angular_test: ^2.0.0
  build_runner: ^0.10.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  mockito: ^3.0.0-beta+1
  pageloader: ^3.0.0
  test: ^1.0.0

```
