### ISSUE TITLE
pub get fails for examples/ng_test/github_issues

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#573]
@matanlurey - there are very particular dependency requirements for the [github_issues app](https://github.com/dart-lang/site-webdev/tree/master/examples/ng_test/github_issues), in particular because of the [dependency on ng_bootstrap](https://github.com/dart-lang/site-webdev/blob/master/examples/ng_test/github_issues/pubspec.yaml#L22-L27):
```yaml
dependency_overrides:
  angular2: 3.0.0-beta+1
  # Required for use of angular2 3.0.0-beta with ng_bootstrap.
  intl: 0.14.0
  markdown: 0.11.2
  reflectable: any
```
Could you take a look, these aren't working now that we've updated ng to >= 3.0.0-beta+1.

Maybe we should drop [ng_bootstrap](https://pub.dartlang.org/packages/ng_bootstrap) in favor of angular_components?

cc @kwalrath
