### ISSUE TITLE
[ng] examples: drop `platform_*` entries from pubspec

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#624]
Update all example pubspec files, **removing**
```yaml
transformers:
    - angular2:
        platform_directives:
            - 'package:angular2/common.dart#COMMON_DIRECTIVES'
        platform_pipes:
            - 'package:angular2/common.dart#COMMON_PIPES'
```
because support for the `platform_*` entries is being deprecated.

See https://github.com/dart-lang/angular2/issues/363 for details.

cc @kwalrath
