### ISSUE TITLE
Tutorial starter app pubspec uses different package name than main.dart and app_test.dart imports

### ISSUE THREAD

**Issue by alechenninger** [dart-lang/site-webdev#762]
It looks like the dart files come from the [quickstart project][1], which expect the project to be named "angular_app", but the pubspec names the project "angular_tour_of_heroes," after the tutorial project:

```yaml
name: angular_tour_of_heroes
description: Tour of Heroes
version: 0.0.1
...
```

```dart
import 'package:angular2/platform/browser.dart';
import 'package:angular_app/app_component.dart'; // Error

...
```

[1]: https://github.com/angular-examples/quickstart
